name: KixsSimpleBackpacks
author: kixmc
version: 1.0.10
main: com.kixmc.backpacks.core.SimpleBackpacks
api-version: 1.16
commands:
  backpacks:
    description: KixsSimpleBackpacks core command
permissions:
  backpacks.getcommand:
    default: op
  backpacks.reload:
    default: op